AutoCancellationToken compliance with documented behaviour
postsharp/Metalama.Community pull request #10
Opened 2023-04-28 15:29 UTC by tg73

Please review in general. In particular:

* f198412b6db69395b8c5f267eb93a38d39a1c33a implements a common "find unique name" pattern. I tried to find a suitable library method, but could not.

Also, as a 3rd party PR, it may be necessary to resolve #5 and #6 before this PR can be merged.

2023-04-28 15:31 UTC, gfraiteur commented
Thank you for submitting. I'll have a look when we'll have a bit of bandwidth, after our stable release.

2023-04-28 19:13 UTC, gfraiteur commented
Note that this project is bogus in essence. It's more a proof of concept than anything usable in production. Here are the problems:
1. It does not take into account `virtual` methods.

    Consider this:
    
    ```cs
     class A {
      abstract Task M();
    }

     class B : A {
      override Task M() => File.ReadAsync("f.txt");
    }
    ```

   To add a `CancellationToken` to `B.M`, it must be done in `A.M`.

2. A proper implementation would need to implement a fixed point algorithm (commonly used in iterative static analysis).
  
    Consider for instance:
    
    ```cs
    Task A() => B();
    Task B() => C();
    Task C() => File.ReadAsync("f.txt");
    ```
    
    The algorithm should add a cancellation token to `C`, then transitively to `B`, then to `A`. This cannot be done with a single-pass algorithm (there needs to be an iterative analysis algorithm followed by a single-pass rewriting algorithm).


The project will remain a demo until these concerns are addressed, and they are not simple.

2023-04-29 07:03 UTC, tg73 commented
Indeed, I agree - this project is great as a proof of concept/demo/learning resource. However, as a learning resource, it might be confusing if the code does not behave as described (quite specifically) in the [readme](https://github.com/postsharp/Metalama.Community/blob/master/src/Metalama.Community.AutoCancellationToken/README.md). I noticed #8 while reading the source code, and this PR followed. But as a bonus, I think that bugfix commits are actually useful for other people as a learning resource because these commits illustrate which lines of code are responsible for a particular behaviour, and how to change that behaviour.

2023-04-29 09:59 UTC, gfraiteur commented
Yep thank you for that.

2023-05-12 07:06 UTC, gfraiteur requested changes
See remarks. Please also add your name to LICENSE.md.

2023-05-12 07:06 UTC, gfraiteur commented on src/Metalama.Community.AutoCancellationToken/Metalama.Community.AutoCancellationToken.Weaver/AutoCancellationTokenWeaver.AddCancellationTokenParameterRewriter.cs
> +                // TODO: Review: finding a unique name is a common pattern. Is there a common library implementation?
Please use `SemanticModel.LookupSymbols`.

2023-05-12 08:39 UTC, tg73 commented on src/Metalama.Community.AutoCancellationToken/Metalama.Community.AutoCancellationToken.Weaver/AutoCancellationTokenWeaver.AddCancellationTokenParameterRewriter.cs
> +                // TODO: Review: finding a unique name is a common pattern. Is there a common library implementation?
This has made me think about the issue of stable method signatures. Existing code might call a transformed method referencing the auto-added `CancellationToken` parameter by name. If the auto-added parameter later changes name due to some other symbol becoming defined, the existing call will be broken. I've seen many APIs which have multiple default parameters, including a default `CancellationToken` parameter, so I'd argue that this is a valid real-world scenario (consider many Azure APIs, eg blob storage APIs which take a default `BlobRequestConditions` and a default `CancellationToken`, where it's quite common for callers to provide only the `CancellationToken` via a named argument).

From this perspective, it could be argued that naming the added `CancellationToken` parameter in a stable and predictable way is more important than avoiding conflict with symbols defined outside the method signature.

Arguably, many coding styles/conventions would avoid conflict at least among type/member/parameter names by rules of capitalization and prefixing, leaving mostly the risk of collision with local symbols in the method body. But this thought opens up the hornet's nest of generating code which is compliant with the target project's prevailing coding style rules.

While all this may be going too far for a demo project, it's interesting to at least discuss how it could be addressed in a real-world scenario.

Your thoughts?

2023-05-12 16:03 UTC, gfraiteur commented
Please see https://github.com/postsharp/Metalama.Community/blob/dev/CONTRIBUTING.md as you asked.

2023-05-12 16:31 UTC, gfraiteur commented on src/Metalama.Community.AutoCancellationToken/Metalama.Community.AutoCancellationToken.Weaver/AutoCancellationTokenWeaver.AddCancellationTokenParameterRewriter.cs
> +                // TODO: Review: finding a unique name is a common pattern. Is there a common library implementation?
Excellent point indeed. I agree. Should we report a warning and skip the parameter introduction in case of lexical conflict? Note that we still need to use [SemanticModel.LookupSymbols](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.semanticmodel.lookupsymbols?view=roslyn-dotnet-4.3.0) for that.

2023-05-12 16:51 UTC, tg73 commented on src/Metalama.Community.AutoCancellationToken/Metalama.Community.AutoCancellationToken.Weaver/AutoCancellationTokenWeaver.AddCancellationTokenParameterRewriter.cs
> +                // TODO: Review: finding a unique name is a common pattern. Is there a common library implementation?
Yes, I was thinking the same thing. I will make it so.

2023-05-12 17:09 UTC, tg73 commented on src/Metalama.Community.AutoCancellationToken/Metalama.Community.AutoCancellationToken.Weaver/AutoCancellationTokenWeaver.AddCancellationTokenParameterRewriter.cs
> +                // TODO: Review: finding a unique name is a common pattern. Is there a common library implementation?
Re adding to `LICESNSE.md`:

Given that this is the first individual contributor addition I wanted to clarify exactly what I should do as there is no equivalent example to follow, and my addition will likely set the example for others to follow.

Do you want me to add a line below `Copyright (c) 2023 SharpCrafters s.r.o and contributors.`? I assume not, as I would be covered by `contributors`.

In the `## Contributors` list, should I add `* Tom Glastonbury` (no period or additional info), or something like `* Tom Glastonbury for contributions to 'Metalama.Community.AutoCancellationToken'.`. Or some other variant? Should I include my github handle?

2023-05-14 09:02 UTC, gfraiteur commented on src/Metalama.Community.AutoCancellationToken/Metalama.Community.AutoCancellationToken.Weaver/AutoCancellationTokenWeaver.AddCancellationTokenParameterRewriter.cs
> +                // TODO: Review: finding a unique name is a common pattern. Is there a common library implementation?
Yes I meant to add your name to the `## Contributors` list. You can link to your Twitter profile for instance.

2023-06-05 15:17 UTC, merged